### ISSUE TITLE
Add skos:*Match alignment to other terms?

### ISSUE THREAD

**Issue by no-reply** [rightsstatements/data-model#20]
We have a few matches to PREMIS and Europeana statements in the existing turtle. We should review this and consider adding links to other statement so there is a consistent level of relation at launch time.

**Comment by anarchivist** [comment]
Do we want to keep this as an open issue?

**Comment by kestlund** [comment]
Unless there are specific vocabularies we want to examine, I would recommend closing.

**Comment by aisaac** [comment]
I think I'd like to keep it open, if just to be sure we're having a rather good (if not complete) coverage of the vocabularies we have already (PREMIS and Europeana).

Unless someone can certify that we have done it already? I feel stupid, but I can't remember, and the completeness/representativeness of our matches is not mentioned in the list of open/closed modeling issues (this I've checked).

**Comment by anarchivist** [comment]
Closing; will be creating new discussion as needed for new alignments.
