### ISSUE TITLE
Add `foaf:logo` for visual icons

### ISSUE THREAD

**Issue by anarchivist** [rightsstatements/data-model#21]
The data on rights statements need to refer to icons, as for Creative Commons license.

Resolved: we will use `foaf:logo`, following the Creative Commons practice (e.g. in https://github.com/creativecommons/license.rdf/blob/master/cc/licenserdf/licenses/creativecommons.org_licenses_publicdomain_.rdf) .

Dependency: Receiving logos from the vendor developing the visual identity.

**Comment by aisaac** [comment]
My reading of the discussion at https://basecamp.com/1768384/projects/5077375/messages/77037043 (after we've got some community feedback on difficulty of using icons) is that this issue can remain postponed for quite a while.

**Comment by anarchivist** [comment]
Propose close `wontfix` based on inconsistent expectation around branding.

**Comment by paul2keller** [comment]
agree with not doing something about this at this point
