### ISSUE TITLE
Add the 'this is not a license disclaimer'

### ISSUE THREAD

**Issue by paul2keller** [rightsstatements/data-model#25]
We currently have a placeholder text of each rights statement (as found  in the detailed list of rights statements) for a short disclaimer that these rights statement are not leaglly operative licenses and are not intended for use as licenses. We are currently discussing the exact language but this will need to be added to the rights statements (below the notices). as such i wonder if this has been taken into account in the data model as this statement is functionally different from the other elements. the disclaimer comes after the notices (skos:note) but is not of the same as the notices. the disclaimer is a calrifying statement about the nature of the rights statement as a whole (so it is similar to what we have in skos:scopeNote) but other than what we have in skos:scopeNote it will need to be displayed on the website (the contents of skos:scopeNote will not be displayed on the website). The question here is how do we model this part of the rights statement?

**Comment by paul2keller** [comment]
here is an example of how this will need to be presented (what i am talking about above is the paragraph at the bottom)

<img width="939" alt="screen shot 2015-09-18 at 14 15 31" src="https://cloud.githubusercontent.com/assets/5593766/9958997/c7f49d06-5e0f-11e5-8c0d-17f0beca9732.png">

**Comment by anarchivist** [comment]
Hi @paul2keller - I think I've asked this before, but is this disclaimer going to be identical across all of the rights statements?

**Comment by paul2keller** [comment]
hi @anarchivist that is indeed the intention

**Comment by paul2keller** [comment]
i have inserted the disclaimer in the google doc with the rights statements, so once the data modeling question has been resolved it can be included here

**Comment by aisaac** [comment]
See some prior discussion on modeling/wording at https://basecamp.com/1768384/projects/5077375/messages/48257478
This is tricky - not purely a modeling issue...

**Comment by anarchivist** [comment]
Closing; decision this was translated text rather than a part of the model itself.
