### ISSUE TITLE
Deal with contract expiry dates on OOC-NC

### ISSUE THREAD

**Issue by anarchivist** [rightsstatements/data-model#26]
We did not have time to reword `OOC-NC` prior to release, so we will not need to support the `date` parameter in implementation. Part of this work is working with the other working group to change the wording of the statements to get the contract expiry date clause to be the last sentence for `skos:definition`.

**Comment by paul2keller** [comment]
@anarchivist we did not have time to deal with it prior to release of the whitepaper, but we are in the process of coming up with coming up with a replacement that is more in line with the structure of other NoC statements (and will have the expiry date at the end of the statement text.

**Comment by anarchivist** [comment]
@paul2keller Do we have a timeline for this work? This question has come up in the context of rightsstatements/rights-app#9 and rightsstatements/rights-app#11.

**Comment by paul2keller** [comment]
not a really firm one. i have just established contact with google to discuss this with them. no idea when we can have a substantive discussion with them, but will keep you updated.
