### ISSUE TITLE
How do we facilitate the creation of language-specific representation?

### ISSUE THREAD

**Issue by anarchivist** [rightsstatements/data-model#43]

**Comment by aisaac** [comment]
this issue is about the possibility to have templates for the human-readable versions of the statements, and how to add language specific statements in the data (per discussion with @anarchivist )

**Comment by puik** [comment]
I'm wondering what's the status of implementing the translations of RS declarations as German and Estonian translations have been finalized.

**Comment by paul2keller** [comment]
We will test the deployment process with the German translation next week. if that does not result in any unforeseen problems then we should be able to deploy the EE version in the week after that

**Comment by puik** [comment]
Great! Will be waiting for the news impatiently ;)

**Comment by anarchivist** [comment]
From @literarymachine on rightsstatements/rights-app#65:

> Have you considered using a platform such as https://crowdin.com/ for localization? They don't support turtle, but work well with `.properties` files and convert them to ISO 8859-1 transparently (using Unicode escapes for unsupported characters).

**Comment by anarchivist** [comment]
Closing; we're using Transifex.
