### ISSUE TITLE
What vocabulary changes require a new version?

### ISSUE THREAD

**Issue by escowles** [rightsstatements/data-model#52]
Based on discussion in https://github.com/rightsstatements/data-model/pull/51, we may not need to create a new version when simply adding terms.  However, there is some concern that substantial additions might still require creating a new version, since they may change the usage of existing statements.

Update the guidelines for creating new versions of the vocabulary with clear instructions on what kinds of changes require a new version.

**Comment by escowles** [comment]
I have copied the existing Changes and Versions section from the technical white paper to an open Google Doc: https://docs.google.com/document/d/1K5PL64QDuCpihRp6k_J8BJ9h1x65VPbuYD7UfuevnJ4/edit

**Comment by anarchivist** [comment]
This should be addressed by the [translation policy](http://rightsstatements.org/en/documentation/translation-policy/) and the most recent version of the technical white paper. We can reopen if not.

**Comment by aisaac** [comment]
For the record, the most recent version at the time we closed: http://rightsstatements.org/files/170106requirements_for_the_technical_infrastructure_for_standardized_international_rights_statements_v1.2.pdf
