### ISSUE TITLE
include "One sentence description of the Rights Statement" in the data model?

### ISSUE THREAD

**Issue by paul2keller** [rightsstatements/data-model#55]
the "One sentence description of the Rights Statement" (a.k.a short description) field from the statements tables that we use in the white paper and in the translation templates is not part of the data model. This feels like something that should be fixed (we are spending ressources on translating these strings) but it may also have been a conscious decision. We may want to discuss this at one of the next occasions where we have both the tech WG and the statements WG present (I.e a steering committee meeting)

**Comment by aisaac** [comment]
Hi Paul, we have started a thread with the Tech WG at https://basecamp.com/1768384/projects/5077375/messages/75056838. We hope to come back with an answer soon. And please don't feel any rush to comment in this thread yourself, as we feel it is a good opportunity for us to re-start some useful technical discussions as a WG.

**Comment by anarchivist** [comment]
Proposal from the 2018-01-22 call is to use `﻿dcterms:description`﻿ to represent this data.

**Comment by aisaac** [comment]
@anarchivist this is just a reminder that we also probably need to do this one before the update for the DE translation.
