### ISSUE TITLE
Error in Estonian translation

### ISSUE THREAD

**Issue by puik** [rightsstatements/data-model#61]
In the [Estonian translation of the NKC declaration](https://github.com/rightsstatements/data-model/blob/a7d496f062bfc8608975c3ce6e5ed330dc4b3b3d/rights-statements.ttl#L583) **there is an error**.

The correct wording should be:

**Objekti kättesaadavaks teinud organisatsioon usub mõistlikkuse piires, et objekti kasutamist ei piira autoriõigus ega sellega seotud õigused, kuid lõplikku kinnitust sellele ei ole.**

I've also sent an email about the issue to Julia et al.

**Comment by aisaac** [comment]
I've been informed that the change has been approved by the Statements WG. This will be implemented soon.

**Comment by aisaac** [comment]
It is now implemented in https://github.com/rightsstatements/data-model/commit/e242993d1d78a977aabfb8c680c97b0e8f9e21ca
We will deploy it in some days, next to other changes in the site.
In the meantime @puik if you want to check the commit above and then close the issue, you are welcome!

**Comment by puik** [comment]
I'll close the issue when it's gone to live ;)
