### ISSUE TITLE
Represent statement IDs using skos:notation?

### ISSUE THREAD

**Issue by osma** [rightsstatements/data-model#62]
Currently the data model seems to use dc:identifier for identifiers such as "NoC-CR". Since the model is heavily SKOS-based, I think these could instead (or additionally) be represented using the [skos:notation property](https://www.w3.org/TR/skos-primer/#secnotations).

The benefit would be e.g. greater visibility and usability (e.g. search by identifier) of these identifiers in SKOS-based tools such as Skosmos.

**Comment by aisaac** [comment]
@anarchivist suggests to have both dc:identifier and skos:notation
@literarymachine and @aisaac agree we should keep existing statements.

**Comment by anarchivist** [comment]
To clarify prefer to use `skos:notation` in addition to `dc:identifier` (as opposed to instead of) to avoid breaking the monotonicity rule.

**Comment by aisaac** [comment]
@osma in fact I have a question to you about this issue.

As you know, skos:notation has this weird requirement for a datatype literal (I was against that 10 years ago, I knew it would backfire ;-) ). 

Needless to say, I don't think that rightsstatements.org has the bandwidth to create and maintain a fully-fledged datatype definition for a very few literals.

With your experience in SKOS-based tools, if just yours, would you advise that we create a 'dake' datatype (i.e. a URI but nothing meaningful attached to it) of that we just use skos:notation without any datatype?

**Comment by aisaac** [comment]
ping @osma :-)

**Comment by osma** [comment]
Thanks for the ping @aisaac . I've never taken the datatype requirement very seriously, and in some SKOS datasets I've used plain literal values for skos:notation. While I don't think it should be a very big effort for RightsStatements to coin  a datatype definition - it's only a few triples after all - I would be OK also with just plain literal values.

**Comment by aisaac** [comment]
Thanks @osma !
I've added skos:notation without datatypes. I hope it will work for you.
Actually I'm curious to see whether implementing the basic solution will trigger any feedback. To be frank I'm not expected the masses to raise and complain about it :-)

**Comment by osma** [comment]
Thanks a lot @aisaac and @anarchivist !
