### ISSUE TITLE
Implement Polish translation

### ISSUE THREAD

**Issue by anarchivist** [rightsstatements/data-model#68]
Ideally complete by the end of April

https://docs.google.com/document/d/1_eSB21TkSS4YFiv654ryNJ7yTxbKbE77KosECHhDR90/edit

**Comment by anarchivist** [comment]
Ready for review:

• https://rightsstatements.github.io/pl/
• https://rights-stg.rightsstatements.org/page/1.0/?language=pl
• https://rights-stg.rightsstatements.org/page/1.0/?language=pl
• https://rights-stg.rightsstatements.org/page/InC/1.0/?language=pl
• https://rights-stg.rightsstatements.org/page/InC-OW-EU/1.0/?language=pl
• https://rights-stg.rightsstatements.org/page/InC-OW-EU/1.0/?language=pl&relatedURL=https://example.com/
• https://rights-stg.rightsstatements.org/page/InC-RUU/1.0/?language=pl
• https://rights-stg.rightsstatements.org/page/InC-EDU/1.0/?language=pl
• https://rights-stg.rightsstatements.org/page/InC-NC/1.0/?language=pl
• https://rights-stg.rightsstatements.org/page/NoC-NC/1.0/?language=pl
• https://rights-stg.rightsstatements.org/page/NoC-CR/1.0/?language=pl
• https://rights-stg.rightsstatements.org/page/NoC-NC/1.0/?language=pl&date=2020-04-04
• https://rights-stg.rightsstatements.org/page/NoC-CR/1.0/?language=pl
• https://rights-stg.rightsstatements.org/page/NoC-CR/1.0/?language=pl&relatedURL=https://example.com/
• https://rights-stg.rightsstatements.org/page/NoC-OKLR/1.0/?language=pl
• https://rights-stg.rightsstatements.org/page/NoC-OKLR/1.0/?language=pl&relatedURL=https://example.com
• https://rights-stg.rightsstatements.org/page/NoC-US/1.0/?language=pl
• https://rights-stg.rightsstatements.org/page/NKC/1.0/?language=pl
• https://rights-stg.rightsstatements.org/page/CNE/1.0/?language=pl
• https://rights-stg.rightsstatements.org/page/UND/1.0/?language=pl

**Comment by aisaac** [comment]
After PR #70 it is good for me, thanks a lot!
